return {
  {
    "nvim-treesitter/nvim-treesitter",
    dependencies = {
      "nvim-treesitter/nvim-treesitter-context",
    },
    branch = "main",
    build = ":TSUpdate",
    lazy = false,
    opts = {
      ensure_installed = {
        "bash",
        "cmake",
        "cpp",
        "css",
        "gitignore",
        "haskell",
        "html",
        "latex",
        "lua",
        "markdown",
        "norg",
        "python",
        "regex",
        "rust",
        "scss",
        "svelte",
        "toml",
        "tsx",
        "typst",
        "vim",
        "vimdoc",
        "vue",
        "yaml",
      },
      sync_install = false,
      ignore_install = {},
      highlight = { enable = true },
      auto_install = true,
      indent = { enable = true },
    },
  },

}
