return {
  {
    "nvim-treesitter/nvim-treesitter",
    dependencies = {
      "nvim-treesitter/nvim-treesitter-context",
    },
    build = ":TSUpdate",
    main = "nvim-treesitter.configs",
    lazy = false,
    opts = {
      ensure_installed = {
        "bash",
        "cmake",
        "cpp",
        "css",
        "gitignore",
        "haskell",
        "html",
        "latex",
        "lua",
        "markdown",
        "norg",
        "python",
        "regex",
        "rust",
        "scss",
        "svelte",
        "toml",
        "tsx",
        "typst",
        "vim",
        "vimdoc",
        "vue",
        "yaml",
      },
      sync_install = false,
      ignore_install = {},
      highlight = { enable = true },
      auto_install = true,
      indent = { enable = true },
      incremental_selection = {
        enable = true,
        keymaps = {
          init_selection = "<C-space>",
          node_incremental = "<C-space>",
          scope_incremental = false,
          node_decremental = "<bs>",
        },
      },
    },
  },

}
